### ISSUE TITLE
Getting a compile error

### ISSUE THREAD

**Issue by tickietackie** [jandrassy/StreamLib#3]
Hey I'm getting the following compile error when using it with PlatformIo. 
Is this issue related to myself or sth. with the library?

.pio/libdeps/nano33iot/StreamLib/src/ChunkedPrint.cpp:55:20: error: invalid conversion from 'uint8_t* {aka unsigned char*}' to 'char*' [-fpermissive]

He is complaining about this line of code:

sprintf_P(buffer - l, (firstChunk ? PSTR("%x\r") : PSTR("\r\n%x\r")), pos); 

When I comment out this line, everything compiles, like I would expect it.

What information do you need to help me out here?

**Comment by JAndrassy** [comment]
yes, sorry. please use the GitHub master version. I fixed this error after the release.
https://github.com/jandrassy/StreamLib/commit/79333385de47909a7c42ded3ee626c82af25c8e3

**Comment by tickietackie** [comment]
Sorry for the late response. This did solve it. Thx.
