### ISSUE TITLE
error: 'class Print' has no member named 'availableForWrite'   return min(out1.availableForWrite(), out2.availableForWrite());

### ISSUE THREAD

**Issue by jan-prez** [jandrassy/StreamLib#4]
Hi I'm using a ESP32 and struggling with this error, any help would be appreciated

**Comment by JAndrassy** [comment]
you forgot to check existing issues. and there is only one.
https://github.com/JAndrassy/StreamLib/issues/2

**Comment by jan-prez** [comment]
Sorry, should have mentioned I tried that workaround but it did not fix it unfortunately.

**Comment by JAndrassy** [comment]
the esp32 Arduino core has availableForWrite for some time now. update.

and it is not possible that that workaround doesn't help

**Comment by jan-prez** [comment]
I chose a different version of my board and it seems to compile now cheers
